from baselines.bilstm import BiLSTM
from baselines.bicond import BiCond
from baselines.crossnet import CrossNet
from baselines.siamnet import SiamNet
from baselines.dan import DAN_Bert
from baselines.toad import TOAD
from baselines.ws_bert import WSBert
from baselines.bert_base import BERTBase
from baselines.tan import TAN
from baselines.textcnn import TextCNN